// <auto-generated />
using System;
using AsynchInnServ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AsynchInnServ.Migrations
{
    [DbContext(typeof(AsynchInnDbContext))]
    [Migration("20210129013906_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AsynchInnServ.Models.Ammenities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ammenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Quadruple Fridge"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mini-Bed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MEGA PACKAGE"
                        });
                });

            modelBuilder.Entity("AsynchInnServ.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "ParadiseFalls",
                            Name = "Yoshi-Inn",
                            PhoneNumber = 1111111,
                            State = "New-New-York"
                        },
                        new
                        {
                            Id = 2,
                            City = "Boonies",
                            Name = "Chum-City-Inn",
                            PhoneNumber = 2222,
                            State = "Flaridah"
                        },
                        new
                        {
                            Id = 3,
                            City = "Cold",
                            Name = "Third-Hotel",
                            PhoneNumber = 1,
                            State = "Alaska"
                        });
                });

            modelBuilder.Entity("AsynchInnServ.Models.HotelRoom", b =>
                {
                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("HotelId", "RoomNumber");

                    b.HasIndex("RoomId");

                    b.ToTable("HotelRoom");
                });

            modelBuilder.Entity("AsynchInnServ.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Layout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Layout = "Green everywhere",
                            Name = "King suite"
                        },
                        new
                        {
                            RoomId = 2,
                            Layout = "For Widdle Babbies",
                            Name = "Jr suite"
                        },
                        new
                        {
                            RoomId = 3,
                            Layout = "Normal layout, idk man",
                            Name = "Normal suite"
                        });
                });

            modelBuilder.Entity("AsynchInnServ.Models.RoomAmmenities", b =>
                {
                    b.Property<int>("AmmenityId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int?>("AmmenitiesId")
                        .HasColumnType("int");

                    b.HasKey("AmmenityId", "RoomId");

                    b.HasIndex("AmmenitiesId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomAmmenities");
                });

            modelBuilder.Entity("AsynchInnServ.Models.HotelRoom", b =>
                {
                    b.HasOne("AsynchInnServ.Models.Hotel", "Hotel")
                        .WithMany("HotelRoom")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsynchInnServ.Models.Room", "Room")
                        .WithMany("HotelRoom")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AsynchInnServ.Models.RoomAmmenities", b =>
                {
                    b.HasOne("AsynchInnServ.Models.Ammenities", "Ammenities")
                        .WithMany("RoomAmmenities")
                        .HasForeignKey("AmmenitiesId");

                    b.HasOne("AsynchInnServ.Models.Room", "Room")
                        .WithMany("RoomAmmenities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
